
#ifndef NULL
#define NULL 0
#endif

#define SDL_INIT_ARGS SDL_INIT_VIDEO|SDL_INIT_JOYSTICK

#define SDL_AUDIO_RATE 22050
#define SDL_AUDIO_FORMAT AUDIO_S16SYS
#define SDL_AUDIO_CHANNELS 2
#define SDL_AUDIO_BUFFER 4096

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
//use default screen bpp. It's faster.
#define WINDOW_BPP 0
#define WINDOW_TITLE "IWBTOR"
#define WINDOW_ICON_TEXT "IWBTOR"
